### ISSUE TITLE
Update the child profile

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-unicef-angola#10]
### Top Bar
- [x] Top Bar: Back arrow {first_name} {middle_name} {surname}

### Avatar and Profile info
- [x] Profile text
  - Row 1: {first_name} {middle_name} {surname}
  - Row 2: ID: {opensrp_id} [interpunct} Age: {age} [days/months]

### Immunizations and services
- [x] Title: IMMUNISATIONS & SERVICES (far left side) DOB: {dob} (far right side): **Should be same as Tunisia, but check the field name for date of birth to make sure it is correct**
- [x] [Add the immunizations to be collected](https://github.com/OpenSRP/opensrp-client-unicef-angola/issues/15) 
- [ ] Prior to entering a immunization: Immunization button is white if vaccination is due, otherwise immunization is grey :DIFFERENT than Tunisia

**Comment by cafootitt** [comment]
@msschroeder Just thinking that this might be way too much pink (or blue):
>> Immunisation button is always the same highlighted color (pink if female, blue if male)

Maybe white buttons would be fine, especially if we're not having the schedules.

@rowo What do you think?

**Comment by msschroeder** [comment]
@cafootitt That makes sense. I have changed it. Thanks!

**Comment by msschroeder** [comment]
Looks good to me! Thanks!
