### ISSUE TITLE
Update the immunizations schedule

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-unicef-angola#15]
- [x] Add the immunization schedule - Vaccination schedule can be found [here](https://docs.google.com/spreadsheets/d/1H4OVOHKS6weCesbzxNAf_nr6rRy-WjZsxdMtCpNPfZo/edit?usp=sharing)
AT BIRTH
 - OPV 0
 - BCG
 - Hepatitis B

2 MONTHS
 - OPV 1
 - PENTA 1
 - PCV 1
 - ROTA 1

4 MONTHS
 - OPV 2
 - PENTA 2
 - PCV 2
 - ROTA 2

6 MONTHS
 - OPV 3
 - PENTA 3
 - PCV 3

9 MONTHS
 - MR 1
 - Yellow Fever

- [ ] There will be no service schedule (i.e. due, overdue, expired)
- [x] You cannot receive OPV 3 before OPV 2, OPV 2 before OPV 1. But, you can receive OPV 1 even if you did not get OPV 0
- [x] You cannot receive PENTA 3 before PENTA 2, PENTA 2 before PENTA 1.
- [x] You cannot receive PCV 3 before PCV 2, PCV 2 before PCV 1.
- [x] You cannot receive Rota 2 before Rota 1.
- [x] You should not be able to administer any vaccine before it age

**Comment by msschroeder** [comment]
QA Oct 29th Release:
- [ ] The vaccine schedules seem a bit off. How are they they calculated?
For 2 months:
- The dob is Feb 3rd. 
- The 2 month vaccinations should be 2 months after the dob. So from my understanding that would be April 3rd, but here it says March 30th?

<img width="340" alt="Screen Shot 2020-11-03 at 3 52 20 PM" src="https://user-images.githubusercontent.com/20777928/97988175-9e95bc80-1ded-11eb-966d-a7b30c4bb3d0.png">

For 4 months:
- The 2 month vaccinations were April 3rd 
- The 4 month vaccinations should be 2 months after the 2 month vaccinations. So from my understanding that would be June 3rd, but here it says May 25
<img width="330" alt="Screen Shot 2020-11-03 at 3 53 03 PM" src="https://user-images.githubusercontent.com/20777928/97988261-bd944e80-1ded-11eb-8d8e-cd1e907b8eb8.png">
th?

For 6 months:
- The 4 month vaccinations were June 3rd 
- The 6 month vaccinations should be 2 months after the 4 month vaccinations. So from my understanding that would be August 3rd, but here it says July 20th
![Uploading Screen Shot 2020-11-03 at 3.53.36 PM.png…]()

**Comment by msschroeder** [comment]
@hamza-vd I am still experiencing the same issue as noted in the last QA. Am I misunderstanding how the schedules are being done, while testing?

**Comment by hamza-vd** [comment]
@msschroeder 
Up to my understanding for immunization a single month is treated as 28 days. So in reference to the above image when OPV2 is given at 03/06/20, OPV3 becomes due at 27/07/20. The reason why its showing 20/06/20 here is that a vaccine relaxation period of 7 days is mentioned in the project properties `vaccine.relaxation.days=7` 

@ellykits correct me if I am wrong or missing something here.

**Comment by msschroeder** [comment]
This is correct. I will close the issue
