### ISSUE TITLE
Remove site characteristics from first log in

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-unicef-angola#2]
- [ ] Remove the site characteristics from the first log in

Screen 1
![Screenshot_20200903-123832](https://user-images.githubusercontent.com/20777928/92099077-beefcd80-ede2-11ea-9af0-da0357c758a3.png)

Screen 2
![Screenshot_20200903-123906](https://user-images.githubusercontent.com/20777928/92099075-bdbea080-ede2-11ea-9303-e0ebe66d7f8d.png)

Screen 3
![Screenshot_20200903-123926](https://user-images.githubusercontent.com/20777928/92099064-ba2b1980-ede2-11ea-92d8-91b385b8498e.png)

**Comment by cafootitt** [comment]
@msschroeder I don't think this is required. Site settings are triggered with the ANC module, so for the standalone child module, this won't need to be done, because it won't/shouldn't be there.

**Comment by msschroeder** [comment]
@cafootitt I didn't know this. It was on the UNICEF Tunisa app I was using to define these issues. That is why it was included

**Comment by msschroeder** [comment]
@ndegwamartin This may then not be required

**Comment by ndegwamartin** [comment]
@msschroeder closing this
