### ISSUE TITLE
Implement the side panel

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-unicef-angola#21]
- [x] Swiping from the left or clicking the hamburger menu opens the side panel
- [x] Title: UNICEF Angola (for now - we will change in the future)
- [x] REMOVE Reports
- [x] Update the out of catchment area with the [immunizations schedule for Angola](https://github.com/OpenSRP/opensrp-client-unicef-angola/issues/15)
<img width="387" alt="Screen Shot 2020-09-21 at 2 44 39 PM" src="https://user-images.githubusercontent.com/20777928/93762916-1b435180-fc19-11ea-99ee-ec1f7303d67f.png">

**Comment by mberg** [comment]
Can we make these changes configurable?

**Comment by msschroeder** [comment]
@mberg This app is not currently very configurable - this would increase the timelines for this tool. But, is probably something we may want to consider for other apps moving forward

**Comment by msschroeder** [comment]
@ndegwamartin Will this still have a tiny LOE with the update to the out of catchment area?

**Comment by ndegwamartin** [comment]
It shouldn't change too much since we already have the implementation in place in the generic child health module for which Angola is a dependency. The extra overhead should just be hooking up the menu item above (and testing that it saves the form correctly)

**Comment by msschroeder** [comment]
QA October 29 Release:
- [ ] Update the languages from French/Arabic/English to English/Portuguese

**Comment by msschroeder** [comment]
Looks good to me
