### ISSUE TITLE
Set up project

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-client-unicef-angola#22]
- [x]  Set up Repository + Codebase
- [x]  Configure gradle build system
- [x]  Travis CI
- [x]  Configure Testing support (Gradle)
- [x]  Configure Test Reporting

**Comment by msschroeder** [comment]
@ellykits Is this done? What is left? I see configure test reporting. Is this correct?

**Comment by ellykits** [comment]
Closing this. All this is done @msschroeder
