### ISSUE TITLE
Server set up and deployment

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-client-unicef-angola#23]
Set up Angola staging server
- [x] Update inventories and deployment scripts
- [x] Server deployment

**Comment by msschroeder** [comment]
We will be using KeyCloak - NOT OpenMRS
This requires only OpenSRP server

**Comment by manutarus** [comment]
@ndegwamartin is this a staging or production?

**Comment by ellykits** [comment]
This should be staging server for develoment @manutarus

**Comment by ndegwamartin** [comment]
This is a new project, we'll probably need all three environments i.e. _staging_, _preview_ and _production_ . 

This item was specifically for Staging since this is what we need to start off on development

**Comment by msschroeder** [comment]
@ellykits I am assuming this is closed. Thanks for you help with this!
