### ISSUE TITLE
Ready the UNICEF Angola app to Play Store before live roll-out in January

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-unicef-angola#32]
We'll need the following:

 - [ ] A short description of the app (up to 80 characters): 
Child and caregiver registration and immunisation tracker (57 characters)

- [ ] Full description of the app (up to 4000 characters) 
Alerta Saúde app was developed for a pilot project assessing the impact of sending SMS vaccine reminders to a child's caregiver to take their child to the health facility on time for the child's vaccination. The app is used by health facility workers to register children and his/her caregivers for enrollment in the pilot project and recording the child's immunizations at the health facility for easy monitoring and evaluation.

Alerta Saúde is powered by OpenSRP (smartregister.org), an open source digital health platform for frontline health workers.
(553 characters)

- [ ] Hi-res app icon (512x512 pixels)
![appicon-512x512](https://user-images.githubusercontent.com/20777928/101675605-16997700-3a6b-11eb-8aa5-cd10568c86ef.png)

- [ ] Feature graphic for the apps. More info on the feature graphic here (1024x500 pixels) Waiting to finalize
![Feature](https://user-images.githubusercontent.com/20777928/102194628-98a3f880-3ece-11eb-92a4-978f9502154a.png)

- [ ] 3 screenshots of the each app @rowo
<img width="299" alt="Screen Shot 2020-12-09 at 10 16 49 PM" src="https://user-images.githubusercontent.com/20777928/101676472-46954a00-3a6c-11eb-83b1-b585f9fa2d71.png">
<img width="299" alt="1 (1) (1)" src="https://user-images.githubusercontent.com/20777928/102194586-8b870980-3ece-11eb-809c-40fd32895d81.png">
<img width="299" alt="2 (1)" src="https://user-images.githubusercontent.com/20777928/102194597-8f1a9080-3ece-11eb-8101-7a0deeb8f423.png">

**Comment by ndegwamartin** [comment]
@msschroeder what are the main features of the app we want to communicate on Playstore for this release? 
We can use a bulleted list for this

**Comment by msschroeder** [comment]
- Child and caregiver registration
- Immunization tracking
