### ISSUE TITLE
OpenSRP Web deployment for Angola

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#35]
- [ ] Create a Web instance for UNICEF Angola.
- [ ] Deploy OpenSRP Web for Angola.

**Comment by dubdabasoduba** [comment]
Do we already have servers set up for OpenSRP?

**Comment by dubdabasoduba** [comment]
Does this have a deadline if so when is it?

**Comment by msschroeder** [comment]
@dubdabasoduba We have production and staging servers - does this have any special requirements other than what is required for OpenSRP?

Deadline: The locations are created on staging server, but not the production server. We are going live on 12th for trainings. So, I would be open to a few options:
1. The first week of January to enable me to add the locations and assign users to teams
2. We do it through the API - but it would require and engineer by the Jan 8th.

Is that possible or not really possible?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba We have production and staging servers - does this have any special requirements other than what is required for OpenSRP?
> 
> Deadline: The locations are created on staging server, but not the production server. We are going live on 12th for trainings. So, I would be open to a few options:
> 
> 1. The first week of January to enable me to add the locations and assign users to teams
> 2. We do it through the API - but it would require and engineer by the Jan 8th.
> 
> Is that possible or not really possible?

Jan 8th will be a bit tricky since most of the engineers with be on leave. 

If I understand this correctly we shall also need to deploy OpenSRP web to production? @ukanga How far are we with the k8s scripts to deploy OpenSRP web? 

Would it make sense to deploy against production the same way we do right now?

**Comment by dubdabasoduba** [comment]
> * [ ]  Create a Web instance for UNICEF Angola.
> * [ ]  Deploy OpenSRP Web for Angola.

What are the URL's to be used for this deployment?
@msschroeder Would you know who deployed this stage instance?

**Comment by msschroeder** [comment]
@dubdabasoduba When you say URLs do you need a different URL than the staging and production servers?
Elly deployed the staging instance

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba When you say URLs do you need a different URL than the staging and production servers?
> Elly deployed the staging instance

Thanks, @msschroeder. I will follow up the rest of the technical stuff with elly

**Comment by msschroeder** [comment]
Closing
