### ISSUE TITLE
Incorporate the Web Administration on Angola

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#36]
- [ ] Incorporate the Web Admin component of Web on Angola.

**Comment by dubdabasoduba** [comment]
Am I right to assume that this just means deploying the Admin pieces we have for Angola and no new work required

**Comment by msschroeder** [comment]
@dubdabasoduba I am not entirely sure. I am not sure I understand what is required to get OpenSRP web deployed. If this issue is not needed in addition to https://github.com/OpenSRP/opensrp-client-unicef-angola/issues/35. We can close

**Comment by dubdabasoduba** [comment]
My question is whether Angola needs more work done other than the admin pieces we already have.

**Comment by msschroeder** [comment]
All I need is the location hierarchy and the assigning of users to that hierarchy so they can log in for the correct health facility

**Comment by dubdabasoduba** [comment]
@ukanga I think Angola just needs deployment of what we have as the admin bits and no new features

**Comment by ukanga** [comment]
Who is able to do this deployments currently? I think you have been the one doing deployments, can you take this on?

**Comment by dubdabasoduba** [comment]
> Who is able to do this deployment currently? I think you have been the one doing deployments, can you take this on?

Yes, I can.

**Comment by msschroeder** [comment]
Closing
