### ISSUE TITLE
Cannot log into an account

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#48]
### Issue
I cannot log into Alerta Saude for one particular account. I am not sure why this is occuring. 

I did the following to troubleshoot:
1. Reset the password to what it should be - https://keycloak.smartregister.org/auth/admin/unicef-ao-production/console (Angola production interface for KeyCloak)
2. Made sure to delete the storage before logging in

However, none of this seemed to work, so I am wondering if this is something else.

To replicate:
1. Download the production https://play.google.com/store/apps/details?id=org.smartregister.unicefangola&hl=en&gl=US
2. Clear the app storage
3. Log in using the share credentials from Megan

**Comment by ndegwamartin** [comment]
@msschroeder It appears this user is not mapped to any organization. 

Here's the corresponding server error:

`User not mapped on any location. Make sure that user is assigned to an organization with valid Location(s)`

**Comment by msschroeder** [comment]
@ndegwamartin It seems that maybe the wrong user id was associated twice. Here is the original file used to create the account -https://drive.google.com/drive/folders/15RquKVAc8MndY5ikIAA-NoBCLjdDq02G?usp=sharing However, I found the account above it has the same user id. When actuality the first account (hcsfvontade) is correctly associated with the right user id and hcmimulevos should be associated with the user id 97b8a469-7ecb-49fa-8818-1259133015c7. Is it possible to update the system? Then, we can see if it works?

**Comment by ndegwamartin** [comment]
@msschroeder this is now fixed

**Comment by msschroeder** [comment]
Closing
