### ISSUE TITLE
Discussion for IT support of Alerta Saude 

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#49]
The project (OpenSRP app) is going to be supported by the government IT team. They have requested access to the following:
1. Creating accounts
2. Delete accounts
3. Reset passwords
4. Track what each account is doing - i.e. when a user logs in, what they entered, etc. - They think this will help to troubleshoot issue easier.
5. Admin password that manages all accounts

I have the following questions about the above request - 
1. Is the KeyCloak production instance separate from other projects for UNICEF Angola?
2. To easily create accounts - What would be required? I am assuming this would require OpenSRP web. Is that correct?
3. If the project requires access to OpenSRP web, what is required to get that configured for UNICEF Angola
4. Is there a way that you can easily track what a user is doing in each account (Point 4)?
5. Is there any sort of admin account or password to manage accounts (Point 5)?
6. Is the KeyCloak site available in Portuguese? If not, is there a way it can be easily translated?
7. Is OpenSRP web available in Portuguese? If not, is there a way it can be easily translated?

**Comment by dubdabasoduba** [comment]
Point 2: **To easily create accounts - What would be required? I am assuming this would require OpenSRP web. Is that correct?** - Yes you will need OpenSRP web

Point 3: **If the project requires access to OpenSRP web, what is required to get that configured for UNICEF Angola** -- Assuming you are just going to use the default modules which are **User management**, **Team Management**,  **Location management** and probably **form configuration** then we the following. For easy tracking please create a separate issue for this deployment. 
    - Access to the server to deploy on to. We will be using the Kubernetes set up. cc: @manutarus 
    - The domain name to be used


Point 5: **Is there any sort of admin account or password to manage accounts**  -- The new Access control work will help us restrict which users have access to the user management module which has the accounts management functions

Point 6: **Is OpenSRP web available in Portuguese? If not, is there a way it can be easily translated?** --- Multi-language support is enabled on OpenSRP but the client will need to translate the web app strings from English to Portuguese

**Comment by ndegwamartin** [comment]
**Point 1: Is the KeyCloak production instance separate from other projects for UNICEF Angola?**
- No the current set up is on shared production
 
**Point 4: Is there a way that you can easily track what a user is doing in each account?**
- This is not implemented yet. There are ongoing discussions internally on how to support this

**Point 5: Is there any sort of admin account or password to manage accounts?**
- In addition to the comment above (See @dubdabasoduba 's comment), account management is possible on Keycloak. 
- The way it would work is, though the Keycloak production instance is shared, an Administrator password can be shared for the Angola deployment only. 
- This will give admin access to the Angola team for user account management via the [Angola realm admin console](https://keycloak.smartregister.org/auth/admin/unicef-ao-production/console)

**NB:** Please note this is only as far as creating the user. Other management items mentioned in the Point 3 comment above will best be managed from OpenSRP Frontend web

**Comment by msschroeder** [comment]
@dubdabasoduba `Point 6: Is OpenSRP web available in Portuguese? If not, is there a way it can be easily translated? --- Multi-language support is enabled on OpenSRP but the client will need to translate the web app strings from English to Portuguese`
How will this be done? And can this be done with the same work as the deployment of OpenSRP web?

@ndegwamartin ```
Point 4: Is there a way that you can easily track what a user is doing in each account?
This is not implemented yet. There are ongoing discussions internally on how to support this
```
Where are these ongoing situation? What has been discussed? Where will updates be provided? Etc.

**Comment by ndegwamartin** [comment]
@msschroeder I've tagged you on the internal communication channel where this was mentioned

**Comment by msschroeder** [comment]
I am closing because the client said that these are not required anymore
