### ISSUE TITLE
Deploying OpenSRP web for UNICEF Angola Alerta Saude Project

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#50]
- [ ] Deploy OpenSRP web to UNICEF Angola Production
- [ ] Port the web string for translation to Portuguese

Requirement:
- When is the deadline for this deployment? 
We have a little flexible, but the sooner the better

 - What URL are we deploying to?
 URL: @ellykits Would you be able to help with this?

- Keycloak realm to be used
Realm: @ellykits Would you be able to help with this?

- OpenSRP server to be used
@ellykits Would you be able to help with this?

- Credentials to login to the realm and to OpenSRP.
Realm log in - Bitwarden - Keycloak Realm Administrator (unicef-ao-admin)
OpenSRP - @ellykits Would you be able to help with this?

We will only be enabling the following modules for this deployment
- User management includes user creation, user groups assignments & creation & roles viewing
- Location management.
- Team management includes adding practitioners to teams, assigning teams to locations

**Comment by dubdabasoduba** [comment]
@msschroeder Please advice your team to start adding the translations [here](https://www.transifex.com/opensrp/opensrp-web/dashboard/)

**Comment by dubdabasoduba** [comment]
> * [ ]  Deploy OpenSRP web to UNICEF Angola Production
> * [ ]  Port the web string for translation to Portuguese
> 
> Requirement:
> 
> * When is the deadline for this deployment?
>   We have a little flexible, but the sooner the better
> * What URL are we deploying to?
>   URL: @ellykits Would you be able to help with this?
> * Keycloak realm to be used
>   Realm: @ellykits Would you be able to help with this?
> * OpenSRP server to be used
>   @ellykits Would you be able to help with this?
> * Credentials to login to the realm and to OpenSRP.
>   Realm log in - Bitwarden - Keycloak Realm Administrator (unicef-ao-admin)
>   OpenSRP - @ellykits Would you be able to help with this?
> 
> We will only be enabling the following modules for this deployment
> 
> * User management includes user creation, user groups assignments & creation & roles viewing
> * Location management.
> * Team management includes adding practitioners to teams, assigning teams to locations

I think this issue is sufficient. Once the required details are added then we can assign this work.

**Comment by ellykits** [comment]
OPENSRP SERVER: https://unicef-ao.smartregister.org/opensrp/
URL: N/A (you may need to create this via terraform I do not think it was created when deploying opensrp)
The rest of the details are available in Bitwarden **(OpenSRP UNICEF Angola collection)** including the realm and client credentials

**Comment by msschroeder** [comment]
This is done - So closing
