### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#51]
UNICEF Angola has users that cannot sync their data easily using mobile data. You hit sync, it starts synchronizing, and then you get a failed synchronization. What can be done for issue where they are trying to sync? What if they have a low mobile data connection? What can be done?

**Comment by msschroeder** [comment]
We have additional information:
1. The user hcentrovia2 is unable to sync data using WIFI in UNICEF office
2. It was unable to sync using mobile data
3. It does not sync in English or Portuguese
4. I have a demo user: demo that can log in on another device and sync with out a problem
5. Device information in the picture below
![WhatsApp Image 2021-04-23 at 16 36 36](https://user-images.githubusercontent.com/20777928/115880001-ecad8380-a452-11eb-81b9-3300d8ccebd0.jpeg)

**Comment by allan-on** [comment]
Hello @msschroeder 
The user didn't have permissions to sync. They didn't have the required role assignment to enable them to sync. I've assigned them the role on Keycloak and when they log out and log in again they should be able to sync

**Comment by msschroeder** [comment]
@allan-on Can we check that all users can sync?

**Comment by allan-on** [comment]
@msschroeder Yeah will confirm and update

**Comment by allan-on** [comment]
I checked and assigned the missing roles for the rest of the users and so they should be able to sync ✅

**Comment by msschroeder** [comment]
Thank you @allan-on the client confirmed they were able to sync. Thank you!
