### ISSUE TITLE
Migrate/Refactor and clean up synced data report implementation to core

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/opensrp-client-unicef-angola#59]
We need to move the implementation on #58 to the client core library for re-use by any implementation

- [x]  Refactor to move all the reusable/generic code to `opensrp-client-core` for reuse by other implementations
- [x]  Unit testing

**Comment by msschroeder** [comment]
Access to DB: https://drive.google.com/drive/folders/1za7HttG325CBvHkOt0wcuoRp4AGGyMyf?usp=sharing - Only @ndegwamartin and Simon have acces. Please let me know if anyone else needs access

**Comment by ndegwamartin** [comment]
**Next steps for the patch:**

- Migrate the Alerta Saúde app to the latest client modules
- Add migration scripts to reset the validation flags of all the client records on the device
- Update App version for release
- Upgrade on device with older version
- Test/Validate patch works for a user X
- Publish the patch to Playstore

**Comment by hilpitome** [comment]
Migration of this functionality to client core was done with PR [#812](https://github.com/opensrp/opensrp-client-core/pull/812) and is now available in opensrp-client-core as from [v4.3.16-SNAPSHOT](https://github.com/opensrp/opensrp-client-core/releases/tag/v4.3.16-SNAPSHOT)
