### ISSUE TITLE
Add cached Vaccine data to the Sync Stats view

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/opensrp-client-unicef-angola#63]
We need to add a view to show the count of Unsynced vaccines on the device (cached vaccines and other events). This would enable us do a safe clean re-install when needed. 

This should render in a widget similar to the implementation [here](https://github.com/opensrp/opensrp-client-unicef-angola/issues/58) , either _within_ or _externally(new widget)_ . Within is preferable but we can temporarily implement one with the lowest LOE for a quick turnaround

The Vaccine and Growth monitoring values get cached before being marked as Syncable. We want to be able to render the count of the cached records. 

- [ ] Implement UI components showing the rendering
- [ ] Fetch the counts of vaccines and growth monitoring records cached

**Comment by ndegwamartin** [comment]
**Tables of interest** 

- Vaccines - `vaccines `
- Recurring Services - `recurring_service_records`
- GM Height - `heights`
- GM Weight - `weights`

The query filter will be `WHERE sync_status != 'Synced'`

**Comment by ndegwamartin** [comment]
**Acceptance Testing**

- Create a new child
- Record Vaccine 
- Record Weight

Check the stats view and confirm that the above counts are:
 - Greater than 0
 -  Equal to the number of vaccines given

**Comment by hilpitome** [comment]
Steps to use the app with the new changes can be found in[ support issue #45](https://github.com/opensrp/support/issues/45#issuecomment-934158297)

**Comment by hilpitome** [comment]
view is now in release[ v0.0.7](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.7)
