### ISSUE TITLE
UNICEF Angola - V0.0.13 Issue Raissed - List doesn't appear after using the Register Search

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#71]
### Project Name
UNICEF Angola

### Description
Version: 0.0.13
When searching for a child using search register and after clearing the search, the other names are not appearing

### Steps to reproduce
1. Open App
2. Type the child's name using the search register and hit search
3. The child's name should appear below 
4. Clear their name - The other's names should appear, but don't
5. If you click the search bar icon again, all the names should now appear 

### Affected OpenSRP Android client and server
Referenced issue: https://github.com/onaio/qa/issues/114

https://github.com/opensrp/opensrp-client-unicef-angola
All Server information saved on Bitwarden Collection OpenSRP UNICEF Angola 

[1st Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/show)
[2nd Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.2)
[3rd Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.3)

### Core developers
Hamza
Elly
Hilary (helped with the 2nd and 3rd release for the support issue)

**Comment by hilpitome** [comment]
This has been fixed by PR#[849](https://github.com/opensrp/opensrp-client-core/pull/849) in opensrp-client-core

**Comment by madrinekariuki** [comment]
This has been tested on [this](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.14) shared apk:
steps:

- Open App
- Type the child's name using the search register and hit search
- The child's name should appear below
- Clear their name 
- Observe if all the names appear.

Observation
After clearing the searched childs Name the other names are appearing as expected.
