### ISSUE TITLE
UNICEF Angola - V0.0.13 Issue Raised - Records appearing without name with bottom Search

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#73]
### Project Name
UNICEF Angola

### Description
Version: 0.0.13
The search icon on the bottom of the page is not showing the child's names after the search.
login, sync and using the bottom search, type in a kids name, observe how on the results some kids do not show name and some do.

### Steps to reproduce
1. Open App
2. Sync
3. Open the bottom search
4. Observe how some children's names do not appear in the results and some do (issue 4 image)

![image](https://user-images.githubusercontent.com/84722169/149779641-351d9144-730a-4557-a24a-fc0b4cc70da4.png)

### Affected OpenSRP Android client and server
Referenced issue: https://github.com/onaio/qa/issues/114

https://github.com/opensrp/opensrp-client-unicef-angola
All Server information saved on Bitwarden Collection OpenSRP UNICEF Angola 

[1st Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/show)
[2nd Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.2)
[3rd Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.3)

### Core developers
Hamza
Elly
Hilary (helped with the 2nd and 3rd release for the support issue)

**Comment by madrinekariuki** [comment]
this has been tested on [this](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.14) apk

steps:

- Open App
- Sync
- Open the bottom search
- Observe how some children's names do not appear in the results 

observations:
after the fixes, all the children's names are appearing after the search.

see screenshot below.
![image](https://user-images.githubusercontent.com/84722169/151547081-69f792c4-d0f4-448e-b31d-81a44f2d2e31.png)
