### ISSUE TITLE
UNICEF Angola - V0.0.13 Issue Raised - Vaccine not transferring between devices

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#74]
### Project Name
UNICEF Angola

### Description
Version: 0.0.13
Vaccine data recorded in one device (android 11) is not showing in the other device (android 8). This is even after a successful and complete sync. This was tested with meek mill and august omar.

### Steps to reproduce
1. Open App on one device
2. Register a child
3. Register a vaccine (i.e. BCG)
4. Sync
5. Open the app on another device
6. The child's vaccines are not appearing

### Affected OpenSRP Android client and server
Referenced issue: https://github.com/onaio/qa/issues/114

https://github.com/opensrp/opensrp-client-unicef-angola
All Server information saved on Bitwarden Collection OpenSRP UNICEF Angola 

[1st Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/show)
[2nd Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.2)
[3rd Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.3)

### Core developers
Hamza
Elly
Hilary (helped with the 2nd and 3rd release for the support issue)

**Comment by hamza-vd** [comment]
@msschroeder 
I have investigated the issue but was unable to reproduce it. The vaccine data recorded is syncing on both devices. I 
 recorded the vaccine on the first device,  manually triggered sync on both devices, and was able to see the recorded vaccine at the second one. However the syncing takes some time (around 15 mins). 

If the requirement is to sync vaccine data immediately then that can also be done.

**Comment by msschroeder** [comment]
@hamza-vd Thank you for checking into to this further - 15 minutes should be fine.
