### ISSUE TITLE
UNICEF Angola - From Subcontractor in Field - Unable to update 4 month vaccination

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-unicef-angola#75]
### Project Name
UNICEF Angola

### Description
Version: 0.0.4
Username: hcmimulevos

PCV 2 can only be added 1 month after PCV1. However, if you add PCV2 and PCV1 and then undo PCV1, you can enter a date for PCV1 that is after the date for PCV2

### Steps to reproduce
1. Open App on one device
2. Register a child
3. Register all 2 months vaccines except PCV1 before today by at least 2 months 
4. Register all 4 months vaccinations with today
5. You will not be able to register PCV2
6. Register PCV 1 with the same date as other 2 months vaccines
7. Register PCV2 with the same date as other 4 months vaccines
5. Undo PCV 1 and register a date after PCV2

### Affected OpenSRP Android client and server
https://github.com/opensrp/opensrp-client-unicef-angola
All Server information saved on Bitwarden Collection OpenSRP UNICEF Angola 

[1st Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/show)
[2nd Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.2)
[3rd Release](https://github.com/opensrp/opensrp-client-unicef-angola/releases/tag/v0.0.3)

### Core developers
Hamza
Elly
Hilary (helped with the 2nd and 3rd release for the support issue)

**Comment by hamza-vd** [comment]
@msschroeder 
I need some clarification on this. What should be the success criteria of this issue? What should happen when a user tries to record PCV1 after the date PCV2 was given?

**Comment by msschroeder** [comment]
@hamza-vd The date for PCV1 should not be less than the PCV2 date. Essentially, the dates for previous vaccines (PCV1, OPV1, etc.) should not be possible to be given after the second vaccinations (PCV2, OPV2, etc.)

**Comment by hamza-vd** [comment]
@msschroeder 
I have a scenario where I can't decide what should be the max date limit for vaccines when "Record All" is selected and the next vaccines given has different dates.

For example, consider the following case:
<img src="https://user-images.githubusercontent.com/70560433/150804291-29caeda5-9273-4290-b741-f3f3727545b3.png" width="450" />

here PCV 2, ROTA 2, and OPV 2 are given at different dates. The max date for OPV 1 will be 22/08/21, for PCV 1 it will be 28/08/21 and for PENTA 1 there will be no limit.  See the below images as well 
<img src="https://user-images.githubusercontent.com/70560433/150805081-338f97a6-c07e-495d-b9f7-57f36a50b932.png" width="450" />
<img src="https://user-images.githubusercontent.com/70560433/150805098-dff1bc1b-8ac5-4d7f-898b-c63e0d2d4552.png" width="450" />

But If I trigger **"Record All"** button, I am unable to decide what should be the max date limit here. 
<img src="https://user-images.githubusercontent.com/70560433/150805444-116d7f74-53b7-417f-82eb-29a50afbc396.png" width="450" />

**Comment by ellykits** [comment]
Record All uses the same date for all the vaccines.

**Comment by hamza-vd** [comment]
@ellykits 
Yes the record all button uses the same date for all, but the issue here is that which max date should be set for the record all button

**Comment by msschroeder** [comment]
@hamza-vd During the meeting with Elly and Martin, we discussed the use case. Essentially, we said that this use case is very limited and highly improbably. Therefore, the complexity you have highlighted vs. the edge case of it actually happening  is limited, we could leave the code as is.
